services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'

    Postyou\ContaoCookiebarOptin\:
        resource: ../src/
        exclude: ../src/{ContaoManager,DependencyInjection}
